### ISSUE TITLE
upgrade to next.js 9.3

### ISSUE THREAD

**Issue by koshuang** [OnrampLab/next-starter#44]
https://sergiodxa.com/articles/next-tailwind/
https://dev.to/notrab/get-up-and-running-with-tailwind-css-and-next-js-3a73
https://spectrum.chat/next-js/general/have-you-set-up-tailwindcss-with-next-9-x~9189159b-bc7b-466f-8ba8-43edd075682f
https://codesandbox.io/s/using-tailwind-with-nextjs-npogn?from-embed

**Comment by TianyiLi** [comment]
#50
