### ISSUE TITLE
Proposal - Auto-redirect to Sign-in/Home page based on Auth state

### ISSUE THREAD

**Issue by rt-cff** [OnrampLab/next-starter#80]
Requirements
When Logged in:
Visiting Sign-in/Sign-up/Forgot page will redirect to Home Page
When NOT Logged in:
Visiting pages other than Sign-in/Sign-up/Forgot will redirect to Sign-in Page

Implementations
- A Hook to redirect & return Auth state - isLoggedIn / isAuthResolve / isAuthPage
- Conditionally Return null to avoid flashing page during redirect due to Auth State.

**Comment by TianyiLi** [comment]
There should be an unauth hook in HTTP module. when the response code gets 403, It means that the authorization incorrect.

**Comment by rt-cff** [comment]
I am referring to the case that, 
the user has properly sign-in(authorized) but visiting auth-related pages such as sign-in.
the user has yet to properly sign-in(authorized) but visiting private pages such as the Dash board. (I think we already have this)

Nothing related to authorization or ACL.
