### ISSUE TITLE
Proposal - Use Redux to manager Auth state

### ISSUE THREAD

**Issue by rt-cff** [OnrampLab/next-starter#81]
Requirements:
- Use Redux to manage Auth state, instead of Context + Provider

Implementations:
- export actions login, logout, refresh token, 
-

**Comment by TianyiLi** [comment]
And, JWT token contains expired time, how redux auto revoke the expired token(or maybe not) then refresh it?

**Comment by rt-cff** [comment]
Redux do not have to handle it, we could still have the setTimeout.
OR
We could have redux to do it and call setTimeout in Login action.
I will have this part of code up asap, so we have something to look at and discuss.

**Comment by rt-cff** [comment]
But the main focus is whether or not we all agree to use Redux to handle this.
